### ISSUE TITLE
ValueError 'Fieldset specified, but not found' on running mr.migrator

### ISSUE THREAD

**Issue by djowett** [thet/programmatic.transmogrifier#2]
```
2015-10-27 13:04:40 INFO Zope Ready to handle requests
['', 'jsonsource', 'typemapper', 'removeid', 'pathfixer', 'disable_versioning', 'constructor', 'schemaupdater', 'uid', 'browser_default', 'latlngupdater', 'local_roles', 'workflowupdater', 'owner', 'enable_versioning', 'reindexobject', 'logger']
('path', '/opt/bda/content_plone_2015-05-25-13-05-16', <zope.schema._bootstrapfields.TextLine object at 0x7f84fc396f50>, u'/opt/bda/content_plone_2015-05-25-13-05-16')
('ignore_path', 'lineage_registry', <zope.schema._bootstrapfields.TextLine object at 0x972f610>, u'lineage_registry')
('delete', 'id', <zope.schema._bootstrapfields.TextLine object at 0x972f590>, u'id')
('stripstring', '/plone/', <zope.schema._bootstrapfields.TextLine object at 0x9730750>, u'/plone/')
('path-key', '_path', <zope.schema._bootstrapfields.TextLine object at 0x9730450>, u'_path')
('prependstring', '', <zope.schema._bootstrapfields.TextLine object at 0x9730610>, u'')
('level', 'INFO', <zope.schema._bootstrapfields.TextLine object at 0x7393090>, u'INFO')
('name', 'PATH', <zope.schema._bootstrapfields.TextLine object at 0x7393c10>, u'PATH')
('key', '_path', <zope.schema._bootstrapfields.TextLine object at 0x827a510>, u'_path')
2015-10-27 13:05:20 ERROR Zope.SiteErrorLog 1445951120.850.677536965988 http://127.0.0.1:8082/plone4/@@mr.migrator-run/@@z3cform_validate_field
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.app.z3cform.inline_validation, line 46, in __call__
ValueError: Fieldset specified, but not found.
> /home/daniel/dev/Plone/Development/buildout-cache/eggs/plone.app.z3cform-0.7.6-py2.7.egg/plone/app/z3cform/inline_validation.py(46)__call__()
-> raise ValueError('Fieldset specified, but not found.')
```

fset = 'none'
Any ideas?
Am I correct in just adding mr.migrator as an egg, rather than a separate part in buildout?

**Comment by djowett** [comment]
I think this requires a backport of [this fix](https://github.com/plone/plone.app.z3cform/commit/045adaadaf9dc491fb7f1f4a22a3675aef095a60) in plone.app.z3cform to the 0.x branch of that product (I'm currently using 0.7.6.

  @thet would value your thoughts on that.  I'm just fighting a subsequent issue to check that I'm correct.

**Comment by thet** [comment]
i actually don't know. the error doesn't sound familiar to me. i'm using plone.app.z3cform 1.0.x, together with plone.app.widgets.
you might backport it :)
or - didn't you mention on slack, that the error is gone with installing plone.app.contenttypes before?

**Comment by djowett** [comment]
The fix was made in 1.0.1, so you probably have it.  But actually it's already in 0.7.7 which I didn't realise existed until just now.  Should we add a pin for >= 0.7.7 in mr.migrator (or perhaps here)? 
I checked and the error still gets thrown if plone.app.contenttypes is installed - though it doesn't stop the migration running.

So I guess really, I should raise this issue in mr.migrator...

**Comment by thet** [comment]
nur sure, if plone.app.z3cform works without plone.app.widgets. try it 
out! if it works, we should make a pin for >= 1.0.1

**Comment by djowett** [comment]
@thet after checking, it _does_ work without plone.app.widgets - only with version plone.app.z3cform = 0.7.7

plone.app.widgets >= 1.0.1  will pull in plone.app.widgets, which users of mr.migrator may not want, 
can I suggest this?:

```
 plone.app.widgets >= 0.7.7,    # or >= 1.0.1 if on 1.x branch
```

**Comment by djowett** [comment]
Fix in https://github.com/collective/mr.migrator/pull/11

**Comment by thet** [comment]
Fixed in: https://github.com/collective/mr.migrator/pull/11
